### ISSUE TITLE
database

### ISSUE THREAD

**Issue by LucHighwalker** [fol-io/backend#4]

**Comment by jayceazua** [comment]
We need to confirm what is in the database before stating it is complete.

**Comment by LucHighwalker** [comment]
It's a controller that I use on multiple apps, it's tested and works.

**Comment by jayceazua** [comment]
The schema, the database, whatever it is, we do not know what are database looks like. Again, it does not even talk to our mobile/frontend. Once this is able to be fully functional then we move it to done, until then it is not done. It is ready, not done.
