### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by LucHighwalker** [fol-io/backend#5]

**Comment by jayceazua** [comment]
We need to make sure that the mobile app can talk to this before stating this is complete.

**Comment by LucHighwalker** [comment]
It is complete and can talk to whatever app wants to talk to it. If it works in postman, it works for anything.

**Comment by LucHighwalker** [comment]
Stop moving these, they are done.

**Comment by jayceazua** [comment]
Brother they are not done if they are not talking to the frontend/ mobile iOS platform.
